name: scwidgets 
channels:
  - conda-forge
  - defaults
dependencies:
- python~=3.11
- pip
- pip:
  - ipywidgets>=8.0.0
  - numpy<2.0.0"
  - widget_code_input @ git+https://github.com/agoscinski/widget-code-input@remove-docstring
  - matplotlib
  - termcolor
