name: Build docs 

on:
  push:
    branches: [main]
  pull_request:
    # Check all PR

jobs:
  tests:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-22.04
            python-version: "3.11"

    steps:
    - uses: actions/checkout@v3

    - Name: Install pandoc
      with:
        sudo apt-get install pandoc

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - run: pip install tox

    - name: run sphinx docs build
      run: tox -e docs 
